"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import {
  Plus,
  TrendingUp,
  FileText,
  CheckCircle2,
  Clock,
  AlertCircle,
  ArrowRight,
  Loader2,
} from "lucide-react";
import { useTranslations, Language } from "@/lib/translations";

export default function EstimatingPage() {
  const { data: session, status: authStatus } = useSession();
  const [lang, setLang] = useState<Language>("EN");
  const [loading, setLoading] = useState(true);
  const [estimates, setEstimates] = useState<any[]>([]);

  useEffect(() => {
    const savedLang = localStorage.getItem("buildr_lang") as Language;
    if (savedLang) {
      setLang(savedLang);
    }
  }, []);

  const { t } = useTranslations(lang);

  useEffect(() => {
    if (authStatus === "authenticated") {
      fetchEstimates();
    }
  }, [authStatus]);

  const fetchEstimates = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/estimates").then((r) => r.json());
      setEstimates(Array.isArray(res) ? res : []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const statusConfig = {
    draft: { label: lang === "EN" ? "Draft" : "Brouillon", color: "bg-gray-150 text-gray-600", icon: <Clock className="w-3 h-3" /> },
    submitted: { label: lang === "EN" ? "Submitted" : "Soumis", color: "bg-blue-50 text-blue-700", icon: <FileText className="w-3 h-3" /> },
    won: { label: lang === "EN" ? "Won" : "Gagné", color: "bg-green-50 text-green-700", icon: <CheckCircle2 className="w-3 h-3" /> },
    lost: { label: lang === "EN" ? "Lost" : "Perdu", color: "bg-rose-50 text-rose-600", icon: <AlertCircle className="w-3 h-3" /> },
  };

  const fmt = (n: number) =>
    new Intl.NumberFormat(lang === "EN" ? "en-CA" : "fr-CA", {
      style: "currency",
      currency: "CAD",
    }).format(n);

  const won = estimates.filter((e) => e.status === "won");
  const wonValue = won.reduce((s, e) => s + e.total_value, 0);
  const submitted = estimates.filter((e) => e.status === "submitted");
  const submittedValue = submitted.reduce((s, e) => s + e.total_value, 0);
  const successRate = estimates.length > 0 ? Math.round((won.length / estimates.length) * 100) : 0;

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] gap-3">
        <Loader2 className="w-10 h-10 text-brand-600 animate-spin" />
        <p className="text-sm font-medium text-gray-500">{lang === "EN" ? "Loading estimates..." : "Chargement des estimations..."}</p>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: t("total_estimates"), value: estimates.length.toString(), color: "text-gray-900" },
          { label: lang === "EN" ? "Success Rate" : "Taux de Réussite", value: `${successRate}%`, color: "text-green-600" },
          { label: lang === "EN" ? "Value Won" : "Valeur Gagnée", value: wonValue > 0 ? fmt(wonValue) : "—", color: "text-brand-600" },
          { label: lang === "EN" ? "In Review" : "En Révision", value: submittedValue > 0 ? fmt(submittedValue) : "—", color: "text-orange-655" },
        ].map((stat) => (
          <div key={stat.label} className="bg-white rounded-2xl border border-gray-150 p-6 shadow-sm">
            <p className={`text-2xl font-extrabold ${stat.color} tracking-tight`}>{stat.value}</p>
            <p className="text-xs font-semibold text-gray-400 mt-1">{stat.label}</p>
          </div>
        ))}
      </div>

      {/* Action bar */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-bold text-gray-900 text-base">{t("estimating")}</h2>
          <p className="text-xs text-gray-400 font-semibold mt-1">
            {lang === "EN" ? "Quantity takeoffs generated by AI from digital blueprints" : "Levés quantitatifs générés par l'IA à partir de plans numériques"}
          </p>
        </div>
        <Link
          href="/estimating/new"
          className="flex items-center gap-2 bg-brand-600 text-white px-4 py-2.5 rounded-xl text-sm font-semibold hover:bg-brand-700 hover:shadow-md hover:shadow-brand-600/10 transition-all duration-200"
        >
          <Plus className="w-4 h-4" />
          {t("new_estimate")}
        </Link>
      </div>

      {/* Empty state */}
      {estimates.length === 0 && (
        <div className="bg-white rounded-2xl border border-gray-100 p-12 text-center shadow-sm">
          <div className="w-14 h-14 bg-brand-50 rounded-2xl flex items-center justify-center mx-auto mb-4 border border-brand-100/50">
            <TrendingUp className="w-7 h-7 text-brand-500" />
          </div>
          <h3 className="font-bold text-gray-900 text-base">{lang === "EN" ? "No estimates yet" : "Aucune estimation pour le moment"}</h3>
          <p className="text-xs text-gray-400 font-medium mt-1.5 mb-5 max-w-sm mx-auto leading-relaxed">
            {lang === "EN" ? "Upload a PDF blueprint and the AI will extract takeoffs in minutes." : "Téléchargez un plan PDF et l'IA en extraira les quantités en quelques minutes."}
          </p>
          <Link
            href="/estimating/new"
            className="inline-flex items-center gap-2 bg-brand-600 text-white px-5 py-2.5 rounded-xl text-sm font-semibold hover:bg-brand-700 transition-colors"
          >
            <Plus className="w-4 h-4" />
            {t("create_first_estimate")}
          </Link>
        </div>
      )}

      {/* Table */}
      {estimates.length > 0 && (
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-gray-50/50 border-b border-gray-100">
                <th className="text-left px-6 py-4 text-xs font-bold text-gray-400 uppercase tracking-wider">
                  {lang === "EN" ? "Estimate" : "Estimation"}
                </th>
                <th className="text-left px-6 py-4 text-xs font-bold text-gray-400 uppercase tracking-wider hidden md:table-cell">
                  {lang === "EN" ? "Items" : "Éléments"}
                </th>
                <th className="text-left px-6 py-4 text-xs font-bold text-gray-400 uppercase tracking-wider hidden lg:table-cell">
                  {lang === "EN" ? "AI Confidence" : "Confiance IA"}
                </th>
                <th className="text-left px-6 py-4 text-xs font-bold text-gray-400 uppercase tracking-wider">
                  {t("value")}
                </th>
                <th className="text-left px-6 py-4 text-xs font-bold text-gray-400 uppercase tracking-wider">
                  Status
                </th>
                <th className="px-6 py-4" />
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {estimates.map((est) => {
                const status = statusConfig[est.status as keyof typeof statusConfig] ?? statusConfig.draft;
                const itemCount = Array.isArray(est.items) ? est.items.length : 0;
                return (
                  <tr key={est.id} className="hover:bg-gray-50/40 transition-colors">
                    <td className="px-6 py-5">
                      <p className="font-bold text-gray-900">{est.project_name}</p>
                      <p className="text-xs font-semibold text-gray-400 mt-1">
                        {est.province} · {new Date(est.created_at).toLocaleDateString(lang === "EN" ? "en-CA" : "fr-CA")}
                      </p>
                    </td>
                    <td className="px-6 py-5 hidden md:table-cell">
                      <span className="text-gray-600 font-medium">{itemCount} {lang === "EN" ? "items" : "éléments"}</span>
                    </td>
                    <td className="px-6 py-5 hidden lg:table-cell">
                      {est.confidence > 0 ? (
                        <div className="flex items-center gap-2.5">
                          <div className="w-20 bg-gray-100 rounded-full h-1.5 overflow-hidden">
                            <div
                              className={`h-1.5 rounded-full ${
                                est.confidence >= 90 ? "bg-green-500" : est.confidence >= 75 ? "bg-amber-500" : "bg-rose-500"
                              }`}
                              style={{ width: `${est.confidence}%` }}
                            />
                          </div>
                          <span className="text-xs font-semibold text-gray-500">{est.confidence}%</span>
                        </div>
                      ) : (
                        <span className="text-gray-400 text-xs">—</span>
                      )}
                    </td>
                    <td className="px-6 py-5">
                      <span className="font-extrabold text-gray-900">{fmt(est.total_value)}</span>
                    </td>
                    <td className="px-6 py-5">
                      <span className={`inline-flex items-center gap-1 px-3 py-1.25 rounded-full text-xs font-bold ${status.color}`}>
                        {status.icon}
                        {status.label}
                      </span>
                    </td>
                    <td className="px-6 py-5 text-right">
                      <span className="text-gray-300 flex items-center gap-1 justify-end">
                        <ArrowRight className="w-4 h-4 hover:translate-x-0.5 transition-transform text-gray-400" />
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Info box */}
      <div className="bg-brand-50 border border-brand-100/50 rounded-2xl p-5 flex gap-4">
        <div className="w-10 h-10 bg-brand-100 rounded-xl flex items-center justify-center flex-shrink-0">
          <TrendingUp className="w-5.5 h-5.5 text-brand-600" />
        </div>
        <div>
          <h3 className="font-bold text-brand-900 text-sm">{t("how_it_works")}</h3>
          <p className="text-brand-700 text-xs font-medium mt-1 leading-relaxed">
            {t("how_it_works_desc")}
          </p>
        </div>
      </div>
    </div>
  );
}
